name: Upload to S3
on: [push]
jobs:
        sync:
                runs-on: ubuntu-latest
                steps:
                        - name: Check out repository code
                          uses: actions/checkout@v2
                        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
                        - run: aws s3 cp ${{ github.workspace }}/ReadMe.md s3://testbucketforjakethekoenig
                          env:
                                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                AWS_DEFAULT_REGION: 'us-west-2'
