name: Upload to S3
on: [push]
jobs:
        sync:
                runs-on: ubuntu-latest
                steps:
                        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
                        - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
                        - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
                        - name: Check out repository code
                          uses: actions/checkout@v2
                        - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
                        - run: aws s3 cp ${{ github.repository }}/ReadMe.md s3://testbucketforjakethekoenig
                          env:
                                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                                AWS_DEFAULT_REGION: 'us-west-2'
